# node:16.16.0-alpine3.16
FROM node@sha256:8cb8d1582f235b30eea033baddde78b17143348fb392154d4c67a3c08307a8f2 as builder
WORKDIR /usr/src/app
COPY --chown=node:node ./package*.json /usr/src/app/
COPY --chown=node:node ./scripts/generate-kms-encrypted-vrf-key.js /usr/src/app/scripts/generate-kms-encrypted-vrf-key.js
RUN npm ci --only=production
USER node
CMD ["node", "scripts/generate-kms-encrypted-vrf-key.js"]