version: '3.8'

services:
  app:
    hostname: algorand-randomness-beacon-app
    image: appliedblockchain/algorand-randomness-beacon-app:latest
    build:
      context: ./services/app
      dockerfile: ./Dockerfile.dev
    depends_on:
      - vrf
    env_file:
      - ./services/app/.env
    network_mode: "host"
    volumes:
      - ./services/app:/usr/src/app

  vrf:
    hostname: algorand-randomness-beacon-vrf
    image: appliedblockchain/algorand-randomness-beacon-vrf:latest
    build:
      context: ./services/vrf
      dockerfile: ./Dockerfile.dev
    env_file:
      - ./services/vrf/.env
    volumes:
      - ./services/vrf:/usr/src/app

