version: '3.8'

services:
  app:
    hostname: algorand-randomness-beacon-app
    image: appliedblockchain/algorand-randomness-beacon-app:latest
    build:
      context: ./services/app
      dockerfile: ./Dockerfile.dev
    depends_on:
      - vrf
    env_file:
      - ./services/app/.env
    network_mode: "host"
    volumes:
      - ./services/app:/usr/src/app
      - /usr/src/app/node_modules

  vrf:
    hostname: algorand-randomness-beacon-vrf
    image: appliedblockchain/algorand-randomness-beacon-vrf:latest
    build:
      context: ./services/vrf
      dockerfile: ./Dockerfile.dev
    depends_on:
      - localstack
    env_file:
      - ./services/vrf/.env
    ports:
      - "50051:50051"
    volumes:
      - ./services/vrf:/usr/src/app
      - /usr/src/app/node_modules


  localstack:
    image: localstack/localstack:latest
    environment:
      - EDGE_PORT=4566
      - SERVICES=kms
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-west-2
      - KMS_REGION=eu-west-2
      - KMS_PROVIDER=local-kms
      - KMS_SEED_PATH=
    ports:
      - "4566-4583:4566-4583"
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ".localstack/kms-data:/tmp/local-kms"
      - "./docker/kms:/init"
