version: 2.1

jobs:
  test-vrf:
    docker:
      - image: cimg/node:lts
        environment:
          NODE_ENV: test
      - image: localstack/localstack:latest
        environment:
          - SERVICES=kms
          - DEFAULT_REGION=eu-west-2
          - KMS_PROVIDER=local-kms
    steps:
      - checkout
      - restore_cache:
          keys:
            - app-{{ checksum "services/vrf/package.json" }}
      - run:
          name: Install dependencies
          command: |-
            cd services/vrf
            npm i
      - save_cache:
          key: app-{{ checksum "services/vrf/package.json" }}
          paths:
            - services/vrf/node_modules
      - run:
          name: Test
          command: |
            cd services/vrf
            npm run test
      - store_test_results:
          path: services/vrf/reports/junit
      - store_artifacts:
          path: services/vrf/reports/coverage

  test-app:
    docker:
      - image: cimg/node:lts
        environment:
          NODE_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - app-{{ checksum "services/app/package.json" }}
      - run:
          name: Install dependencies
          command: |-
            cd services/app
            npm i
      - save_cache:
          key: app-{{ checksum "services/app/package.json" }}
          paths:
            - services/app/node_modules
      - run:
          name: Test
          command: |
            cd services/app
            npm run test
      - store_test_results:
          path: services/app/reports/junit
      - store_artifacts:
          path: services/app/reports/coverage

  test-build:
    docker:
      - image: cimg/node:lts
        environment:
          NODE_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - app-{{ checksum "services/app/package.json" }}
      - run:
          name: Run docker build
          command: |-
            docker-compose -f docker-compose.yml build --exit-code-from build

workflows:
  test-services:
    jobs:
      - test-app
      - test-vrf
      - test-build
