apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: vrf
  name: vrf
  namespace: app
spec:
  selector:
    matchLabels:
      app: vrf
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: vrf
    spec:
      restartPolicy: Always
      containers:
        - name: vrf
          image: appliedblockchain/algorand-randomness-beacon-vrf:latest
          imagePullPolicy: Always
          env:
          - name: SERVICE
            value: "vrf"
          - name: NODE_ENV
            value: "prod-a"
          - name: LOG_LEVEL
            value: "debug"
          - name: AWS_REGION
            value: "eu-west-1"
          - name: AWS_ACCESS_KEY_ID
            value: "AKIAUCFCNNDP43FOEMXL"
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: app-env-vars
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_KMS_KEY_ID
            value: "mrk-16204a3cd38f4c1c8c0a523b9ba10bf2"
          - name: VRF_ENCRYPTED_KEY
            valueFrom:
              secretKeyRef:
                name: app-env-vars
                key: VRF_ENCRYPTED_KEY
          - name: GRPC_ADDRESS
            value: "0.0.0.0"
          - name: GRPC_PORT
            value: "50051"
          - name: SENTRY_DSN
            value: "https://0cdc8ad8aea54dbbbad3dd3b7bec531f@o1305787.ingest.sentry.io/6622570"
          - name: DD_ENV
            value: "prod-a randomness-oracle-env-02-b-eks"
          - name: DD_VERSION
            value: "0.0.1"
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_TRACE_AGENT_PORT
            value: "8126"
          - name: DD_LOGS_INJECTION
            value: "true"
          ports:
            - name: http
              containerPort: 50051
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        eks.amazonaws.com/nodegroup: randomness-oracle-env-02-a-nodes-app
