apiVersion: v1
kind: Secret
metadata:
  name: app-env-vars
  namespace: app
stringData:
  ALGOD_TOKEN: bf70e81486190ee3ef8f3bfef0caedebc4ee159f7fae6e46bd7fb2a55ff38989
  SERVICE_MNEMONIC: rare, virtual, curtain, fun, boost, film, multiply, frost, solid, celery, crumble, rebuild, happy, since, hen, lemon, clerk, route, page, digital, abandon, meadow, logic, above, butter
  AWS_SECRET_ACCESS_KEY: JGaTdz/W181uL1DaZgvnogeFhuJeKfBBMBkpjh2l
  VRF_ENCRYPTED_KEY: AQICAHipek0a6lAm52XNlGyqCwLep0ckIk7UK5liO4liTvK2ZgEDwqGq79ocQwoYgUeDtiQLAAAAojCBnwYJKoZIhvcNAQcGoIGRMIGOAgEAMIGIBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDDnOwqxLeJG2w0/cJwIBEIBbenR/43G7FbUZeB3DiAURHVrZGNO9jE96/J/KgWL3J7F3ghcjQKQDXuXQHKrufu9X+ak8TLA7v/jKd9obPTF9Uf0vuagyWBXKxTCPuPxWOwWl5fP7vZii0gIb2Q==
  


