apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: app
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJhYmRlcGxveWVyIiwicGFzc3dvcmQiOiJtNGx5YWh2eXNuaTA5MzBpaHhkOCIsImVtYWlsIjoiYWItZGVwbG95ZXJAdHV0YW5vdGEuY29tIiwiYXV0aCI6IllXSmtaWEJzYjNsbGNqcHROR3g1WVdoMmVYTnVhVEE1TXpCcGFIaGtPQT09In19fQ==
type: kubernetes.io/dockerconfigjson