apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: app
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllXSmtaWEJzYjNsbGNqSTZRWHA0TkdoelFVcFlVR0ppUW1waFMyNVZZVkZhYVRsaWNVYz0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson