apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      labels:
        app: app
    spec:
      restartPolicy: Always
      containers:
        - name: app
          image: appliedblockchain/algorand-randomness-beacon-app:latest
          imagePullPolicy: Always
          env:
          - name: NODE_ENV
            value: ""
          - name: LOG_LEVEL
            value: ""
          - name: ALGOD_TOKEN
            valueFrom:
              secretKeyRef:
                name: app-env-vars
                key: ALGOD_TOKEN
          - name: ALGOD_SERVER
            value: ""
          - name: ALGOD_PORT
            value: ""
          - name: APP_ID
            value: ""
          - name: SERVICE_KEY
            valueFrom:
              secretKeyRef:
                name: app-env-vars
                key: SERVICE_KEY
          - name: STARTING_ROUND
            value: ""
          - name: VRF_GRPC_HOST
            value: "vrf-hostname"
          - name: "SENTRY_DSN"
            value: "https://0cdc8ad8aea54dbbbad3dd3b7bec531f@o1305787.ingest.sentry.io/6622570"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        eks.amazonaws.com/nodegroup: randomness-oracle-env-03-nodes-app
