apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vrf
  name: vrf
  namespace: app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vrf
  strategy: {}
  template:
    metadata:
      labels:
        app: vrf
    spec:
      restartPolicy: Always
      containers:
        - name: vrf
          image: appliedblockchain/algorand-randomness-beacon-vrf:latest
          imagePullPolicy: Always
          env:
          - name: NODE_ENV
            value: ""
          - name: LOG_LEVEL
            value: ""
          - name: AWS_REGION
            value: ""
          - name: AWS_ACCESS_KEY_ID
            value: ""
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: app-env-vars
                key: AWS_SECRET_ACCESS_KEY
          - name: VRF_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: app-env-vars
                key: VRF_SECRET_KEY
          - name: "SENTRY_DSN"
            value: "https://0cdc8ad8aea54dbbbad3dd3b7bec531f@o1305787.ingest.sentry.io/6622570"
          ports:
            - name: http
              containerPort: 50051
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        eks.amazonaws.com/nodegroup: randomness-oracle-env-03-nodes-app
